### ISSUE TITLE
Mark searched tile/coordinate and picked location.

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/erdblick#113]
Currently, Jump-to-Tile/Coordinate does not allow the user to visually see the exact location or searched coordinate. For this purpose, the coordinate/tile extent should be displayed. This can be achieved, by allowing jump target functions to return a rectangle (for tiles) or a point (for locations). Either will be displayed once the jump action is executed.

**Comment by Waguramu** [comment]
Add coordinates display and a place-able marker
