### ISSUE TITLE
Enhancement of Feature Search and Display Capabilities

### ISSUE THREAD

**Issue by MisterGC** [ndsev/erdblick#13]
The existing feature search in our map viewer currently supports conditions based on attribute values, which helps in extracting a range of features like 'All roads with a speed limit < 50 km/h'. This feature request is aimed at extending the current search and display capabilities, by incorporating more specificity and flexibility. This will ultimately aid in more precise visualization and analysis of the map data.

Details:

**1. Precision Marking of Feature Validity:** 

Current Situation: If an attribute has a defined validity like 'speed limit only valid for the first 50 meters of the road', the entire feature (road) is highlighted in the results.

Desired Enhancement: When the validity of a feature attribute is specific to a part of the feature, only that specific part should be highlighted or marked. For instance, if the speed limit is only valid for a specific stretch of the road, just this stretch should be marked instead of the entire road.

**2. Extraction of Values in Searches:**

Current Situation: The existing search functionality operates on a boolean basis (hit or miss).

Desired Enhancement: The search should allow for the extraction and display of attribute values. For instance, users should be able to request 'show the speed limits (as labels) of all roads that have a speed limit > 50' and get these values visibly marked on the map.

**Comment by MisterGC** [comment]
Originally this request also covered heatmaps - I have now added a separate issue for that which expands this concept of coloring beyond heatmaps - have a look at #16

**Comment by josephbirkner** [comment]
Idea two I think is covered by the filter-based label generation approach. I would move that to a separate issue. I think this issue should focus on aspect one, and we simply call it validity-based search results?

**Comment by josephbirkner** [comment]
Follow-up issue: Allow setting the feature search scope to Attributes or Relations
