### ISSUE TITLE
Direct Access to Inspect All SourceDataLayers of a Tile

### ISSUE THREAD

**Issue by MisterGC** [ndsev/erdblick#160]
Current behavior requires selecting a feature with a reference to a source data layer to inspect all SourceDataLayers of a map tile. This issue proposes adding a method (e.g., context menu, selectable tile proxy) to directly access and inspect all associated SourceDataLayers.

**Comment by josephbirkner** [comment]
UI Concept:
![image](https://github.com/user-attachments/assets/76e19df9-947a-4d88-b127-b87d6b10ff79)

We can also think about a button that allows the User to open this dialog (other than through the context menu).
