### ISSUE TITLE
Display constant names instead of numeric values for special speed limit cases

### ISSUE THREAD

**Issue by artemkulyk** [ndsev/erdblick#161]
Currently, speed limits are displayed as numeric values, including actual speed limits and special cases like 0, 254, and 255.

To improve user convenience, display “0 (SPEED_UNDEFINED)” instead of “0”, “254 (SPEED_VARIABLE)” instead of “254”, and “255 (SPEED_UNLIMITED)” instead of “255” for SPEED_LIMIT_* attributes.

<img width="1552" alt="Screenshot 2024-10-11 at 22 00 41" src="https://github.com/user-attachments/assets/847cae32-0d0b-4fc6-bb04-2db131b50d40">

**Comment by josephbirkner** [comment]
Moved here: https://youtrack.nds-association.org/issue/MAPV-278/Display-constant-names-instead-of-numeric-values-for-special-speed-limit-cases
