### ISSUE TITLE
Loading indicators now disappear when loading is done

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/erdblick#23]
Currently, Erdblick shows dot-indicators for each tile that is marked as to-be-fetched. However, the indicator is not removed once the tile is fetched, reducing the usefulness of the indicator. By also removing the dot, its meaning would be clearly "This tile is marked for loading but has not been received yet". This also covers loading multiple layers for one tile, so when all the layers have been loaded the dot disappears.

**Comment by fklebert** [comment]
It is also not clear why the dots are in different colors at the moment. It gives a wrong hint that they may be in different loading stages or whatever.
In addition they should be only visible either in Debug mode or get an own toggle to be able to completely hide them.

**Comment by MisterGC** [comment]
How do we handle one tile but from multiple sources? 
Some ideas:
- Keep the loading indicator even if the first tile has been fetched but more requests are ongoing?
- Put a number next to indicator to see how many requests are ongoing
- Remove the indicator as soon as the first tile layer has been rendered 

Can we keep the indicator with a special color and/or label when there is no data at all? Just some empty space could cause confusion - seeing something 'n/a' or 'no data' is much clearer - so the user can be sure that's not a problem with the map display.
