### ISSUE TITLE
Responsiveness while parsing long-running tile streams

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/erdblick#24]
The frontend seems to stall occasionally while tile streams are processed. We need to change how visualisation vs. parsing tasks are prioritized while tiles are coming in, to prevent the browser from skipping frames in favor of processing events. This also relates to #25

**Comment by josephbirkner** [comment]
Some thoughts:
* Maintain original blob from tile layer stream instead of re-serializing the tile.
* Make tile requests in smaller batches instead of aborting a large one.

**Comment by MisterGC** [comment]
Have a also a look a the DisplayDistanceConditions: https://github.com/CesiumGS/cesium/blob/main/Apps/Sandcastle/gallery/Distance%20Display%20Conditions.html#L82 - I have not investigated if it works, but a simple approach could be to add an entity with a rectangle that is always displayed as soon as it is clear if there is or isn't content for a tile and then update the entity by adding another representation and adjusting the display distance conditions.

**Comment by josephbirkner** [comment]
Unfortunately, the DistanceDisplayCondition requires that the geometry has already been fully created, which is the thing we need to do lazily. For now, I am settling on the following two improvements, which will be implemented in this ticket:

* No more redundant serialization: The FeatureTile is constructed directly with a blob, not with a serialized representation. This means, that the deserialized WASM representation will only ever be used briefly, and should improve visualization speeds by 30-50%.
* Two-stage visualization: Maintain a load-set separately from the (high-detail) visualization set. This will be the top N tiles from the set of visible tiles. HD visualization tasks come after all tiles have been loaded. A loaded tile is visualized as a dot. This also touches on #23 . The question is, whether the dots represent a loading step indication, or an low-res geometry representation. I think the following makes sense:
  * For tiles-to-be-loaded, a gray dot is shown only if a debug setting is enabled.
  * For loaded non-empty tiles, a green dot is shown, if the tile is not visualized in HD.
  * For loaded empty tiles, a blue dot is always shown.
