### ISSUE TITLE
Toggle for Cesium OSM Layer

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/erdblick#27]
Currently, erdblick comes with the Cesium OSM layer enabled by default. This makes the frontend generally more useful and visually appealing, but prevents offline use-cases and distracts from the actual data that is being displayed. A UI toggle would probably add a lot of user value here.

**Comment by MisterGC** [comment]
I'd extend this one to a slider which is only shown when the osm layer is activated, it will allow to control alpha value. And what about remembering this setting too (see #69)?
