### ISSUE TITLE
Zoom-to-Content/Coverage Functionality

### ISSUE THREAD

**Issue by MisterGC** [ndsev/erdblick#6]
To simplify navigation and inspection of map data, the system should include a 'zoom-to-content' or 'zoom-to-coverage' feature in the map viewer component. This would allow users to instantly zoom to the extent of all displayed data, the complete coverage of the map, or the coverage of the cache, depending on the available data and user preference.

This feature should include at least two functionalities:
1. 'Zoom to All Displayed Data': This function will adjust the map view to encompass all currently displayed map data.
2. 'Zoom to Complete Coverage': This function will adjust the map view to display the entire coverage of the map, or in cases where this information is not directly available, to the coverage of the cache from all activated map sources.

Users should be able to access these functions through an intuitive interface within the map viewer, possibly associated with shortcut keys or key combinations for quick activation.
 
Implementing this feature would allow users to quickly view the full extent of the map data and understand the scope of the data coverage without having to manually navigate or look up coverage information, enhancing the usability and efficiency of the map viewer.

**Comment by josephbirkner** [comment]
"Zoom to all displayed data" is a bit unclear. The displayed data is the data you currently see. What am I missing?

**Comment by fklebert** [comment]
I think "zoom to all displayed data" means zoom to whats currently in the cache.
