### ISSUE TITLE
Encode camera/layer state in URL

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/erdblick#69]
Currently, Erdblick always resets to a default state and camera perspective upon reloading. This should be improved, such reloading never leads to a change of perspective or visible map layers.

The following information should be stored in the URL:
* Camera state information as needed by Cesium. It should be allowed to specify only a subset of this state, e.g. longitude and latitude, while the pitch/yaw/altitude assume default values.
* Active map layers and their respective display levels.

**Comment by MisterGC** [comment]
And in addition the set of activated styles (#76) and the OSM Layer setting (#27)
