### ISSUE TITLE
Responsive layout

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/erdblick#70]
Currently, there is no special layout for narrow views. However, this will be needed to support mobile devices and split-screen map display.

**Comment by MisterGC** [comment]
Do we need to specify more?

**Comment by MisterGC** [comment]
<img width="1230" alt="image" src="https://github.com/ndsev/erdblick/assets/2118573/90ccc39c-ffc5-43a5-8dd4-d4ca9fdaa13c">
Shows both the new default layout as well as the one for portrait mode.
