### ISSUE TITLE
Improve map layer selection panel

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/erdblick#71]
The map layer selection panel needs various UX improvements:

* When folding out, it should not cover the toggle button, so it can be closed again without moving the mouse.
* It should not be a dialog, instead it should just be a plain panel which grows in vertical size as the number of contained map layers increases.
* Currently, it is not possible to toggle a map layer or a whole map on or off. The panel should present a show/hide button in line with each map and nested map-layer.

We should also use this opportunity to move the map layer panel into its own angular component.

**Comment by MisterGC** [comment]
Additions:
* change the focus icon (magnifier glass!?), if I wouldn't know i'd associate the current one with show/hide
* the show/hide could then be just that eye (and crossed out or closed for not showing)
* show the icons next to the text entry not as a "fat" icon
* Change the Add a label: "Tile Level" or  "Zoom Level" before the zoom level selector
* Make the control less bulky

**Comment by MisterGC** [comment]
<img width="496" alt="image" src="https://github.com/ndsev/erdblick/assets/2118573/96603a3a-aff5-46b9-a80f-a0c55c0d5a7b">
Mockup we agreed on
