### ISSUE TITLE
Configuration of proprietary jump targets

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/erdblick#72]
In the context of the NDS mapviewer, erdblick needs to support jumping to packed tile IDs and NDS coordinates, which are closed-source formats. For this purpose, erdblick should read a set of extension module URLs from the URL `./config.json`. This JSON should have an `{extensionModules: [...]}` key. Each extension module is simply a URL which will be dynamically imported.

Each imported JS extension module must export a `getExtension` function, which returns an object the corresponds to the `ExtensionModule` interface. This interface should offer a `jumpTargets` key, which is a list of JumpTarget interface objects. A jump target object consists of (1) a `canJump` function, which checks if the input would be valid, and (2) an `jump` function which performs the jump given a user input string and a cesium view.

**Comment by MisterGC** [comment]
- unify `canJump` and `jump` and use something like `toTargetCoords` which returns an actual result it the target input is supported and `null` otherwise 
- the actual result is lon, lat, alt
- grey out jumpTargets that are not supported for the current user input
