### ISSUE TITLE
Bad scalability/performance when using Firefox (larger viewport/many tiles).

### ISSUE THREAD

**Issue by MisterGC** [ndsev/erdblick#73]
When using Firefox and dealing with viewports with many tiles and a big amount of data, the UI sometimes hangs or lags significantly. In contrast with Chrome I experience continuous/iterative viewport updates that are faster and non-blocking. Why is this the case? Can we we do about it?

**Comment by josephbirkner** [comment]
Performance improved a lot after lowering the concurrency for mapget-datasource-live, so we are closing this for now.
