### ISSUE TITLE
Styling system supports advanced feature relations.

### ISSUE THREAD

**Issue by MisterGC** [ndsev/erdblick#75]
We need to update our styling system to enable dynamic styling based on the advanced feature relations defined in the enhanced Feature Model API (see [Advanced Feature Relations API](https://github.com/ndsev/mapget/issues/53)) . Specifically, the system should allow users to define styles that respond to user interactions with map features. For instance, when a user selects feature A, all related features defined by the relation type 'is visible from, ID of other feature, stretch on other feature’s geometry' should automatically be highlighted in a distinct color. Importantly, this highlighting should apply only to the relevant stretches of geometry that meet the specified relational criteria, not the entire feature. This capability will enable users to visually distinguish and understand these complex relationships at a glance.

**Comment by josephbirkner** [comment]
> How to cover the following scenario: there are multiple sets of features, within each set the features share the same value for some attribute, basted on this I want to color the set. I want to have distinct colors for different sets, so that for example if two sets are (geographically) quite close to each other I can still see that these are two different sets.

I think this is covered by the colormap simfil function. We could even introduce a `colormap()` without parameters, which simply assigns each unique value a unique color (perhaps based on the bash of the value).

**Comment by josephbirkner** [comment]
I would envision the following set of changes:

* For the rule `type` field, allow to specify `relation` and `center()` (indicating that the rule is about visualizing relations).
* The simfil evaluation context for relation rules is the relation object. The relation's `source` and `destination` fields are resolved to the actual feature objects if available.
* The default mode of visualizing a relation is by using a line from the center of the source geometry (or source feature) to the center of the destination geometry (or destination feature).
* The source and destination points may be enriched using additional rules under the `relation-src` and/or `relation-dst` fields. The simfil evaluation context for these rules is the respective feature itself.
* To label the relation line, `relation-label: true` (and then further `label-*` fields) may be set.
* Cross-tile feature references: This involves a (bulk?) `GET locate` and potential tile load requests for every external feature src/dst reference. TBD: We need to prevent externally loaded tiles from loading new external tiles ad infinitum.
* TBD: Showing relations only on selection? I would relay this to a future feature, when we implemented selection-dependent rules.
