### ISSUE TITLE
Precision problems on ARM64 Apple devices.

### ISSUE THREAD

**Issue by MisterGC** [ndsev/erdblick#78]
This has been identified as an issue which applies to CesiumJS in general - this issue is a reminder and probably will be fixed with a newer version of CesiumJS.

- I have reported it here: https://github.com/CesiumGS/cesium/issues/11603 
- there is a longer discussion referencing multiple reports: https://github.com/CesiumGS/cesium/issues/9417
- within this issue there is also a workaround described which seems to help: https://github.com/CesiumGS/cesium/issues/9417#issuecomment-1849221819

Depending on how many users suffer and how fast the problem will be fixed, we may consider doing something about it.

**Comment by josephbirkner** [comment]
Fixed by upgrading to Cesium r115.
