### ISSUE TITLE
Support validity geometry display

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/erdblick#82]
Feature attribute validity geometries are currently not displayed. To support their visualization, `geometry: attribute` shall be allowed as a style rule option. The used geometry will be the attribute's validity, or the feature geometry as a fallback. An attribute rule has the attribute as the simfil evaluation context. It will also be possible to access the parent feature under the `$feature` variable. Selecting an attribute visualization should highlight the corresponding validity node in the attribute tree, and vice versa.

**Comment by MisterGC** [comment]
Maybe start with only showing validities of attributes that get selected in the inspection panel, don't support selecting validities within the viewer.
